language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  -pip install -r Projects/P2/requirements.txt
#Commands
script:
  -python -m unittest discover -s Projects/P2/src/Tests
branches:
  only:
    -main