language: python

python:
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

install:
  -pip install -r requirements.txt
#Commands

script:
  -python -m unittest discover -s Tests

branches:
  only:
    -main